schema: "classroom50/repo-config/v1"
classroom: "cprog"
assignment: "i-know-flowchart"
owner:
  username: "JohanEmilFR"
  id: 320676550
  accepted_at: "2026-09-05T21:50:56Z"
source:
  owner: "geko-crooms"
  owner_id: 316422449
  repo: "i-know-flowchart"
  branch: "main"
